### ISSUE TITLE
Themes website does not have a favicon

### ISSUE THREAD

**Issue by prakharb5** [t1m0thyj/WDD-website#1]
Currently, the website www.windd.info/themes does not have a favicon which appears in the tab description of a browser.

![image](https://user-images.githubusercontent.com/51435948/115525274-90106400-a2ac-11eb-95a6-d3c03c6ec4ad.png)

![image](https://user-images.githubusercontent.com/51435948/115525374-a9191500-a2ac-11eb-9c5a-85092d81307a.png)

Adding the WDD app logo would look great!

**Comment by t1m0thyj** [comment]
Good idea! I added a favicon in https://github.com/t1m0thyj/WDD-website/commit/b33a89b88c86f35d25583fb2596390f0335581bc, but it seems to only work in Firefox and not in Chrome-based browsers 🤔

**Comment by t1m0thyj** [comment]
Fixed in https://github.com/t1m0thyj/WDD-website/commit/47c594928dd1dafe6444ed80d9feb0144c2324dc, it should work in all browsers now.
