### ISSUE TITLE
[Theme-Submitter] is over-sensitive to Brightness 

### ISSUE THREAD

**Issue by AnAceCase** [t1m0thyj/WDD-website#6]
I am attempting to submit a theme via the theme submitter and I am repeatedly getting the error "Brightest image is shown at noon and darkest image is shown at midnight" I have ensured that this is the case yet I continue to get the rejection email with this reason.

I have also edited the JSON and the content of the .DDW and this doesn't change anything

https://www.mediafire.com/file/hzc3ktqkxtwlr1y/Abstract_Sleepy_Mountains.ddw/file

**Comment by t1m0thyj** [comment]
Sorry for the trouble, this issue should now be fixed in the theme submitter and your theme has been added to the site 🙂
